# Generated by Django 5.0.6 on 2024-07-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaApp', '0002_remove_alumno_id_remove_usuario_id_alter_alumno_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='id',
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, unique=True),
        ),
    ]
